blog/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path,include
from home.views import home_view
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home_view, name='home'),
    path('post/', include('post.urls',namespace='post')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    
    path('contact/', include('contact.urls')),
    
    

]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/post/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
    
    path('index/', views.post_index,name='index'),
    path('create/',views.post_create,name='create'),
    path('<slug:slug>/', views.post_detail,name='detail'),# arama motorunda ip/post/id(rakam olacak) girildiğinde girilen id' ye ait postun detay sayfasına gider cunku her post primary key olarak id alıyor
   
    path('<slug:slug>/update/',views.post_update,name='update'),
    path('<slug:slug>/delete/',views.post_delete,name='delete'),

]

blog/post/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class Post(models.Model):
    #id = models.AutoField(primary_key=True) bu kısmı olusturmaya gerek yok django zaten default olarak id'yi primary key olarak atıyor
    user = models.ForeignKey('auth.User', verbose_name='yazar', related_name='posts', on_delete=models.CASCADE)

    title=models.CharField(max_length=120,verbose_name='Başlık')
    content=models.TextField(verbose_name='içerik')
    publishing_date=models.DateTimeField(verbose_name='Yayınlanma tarihi',auto_now_add=True)
    slug = models.SlugField(unique=True, editable=False, max_length=130)
    views_count = models.IntegerField(default=0)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.title
    
    def increase_views(self):
       self.views_count += 1
       self.save()


    def get_absolute_url(self):
        return reverse('post:detail', args=[str(self.slug)])
    
    def get_create_url(self):
        return reverse('post:create')
    
    def get_update_url(self):
        return reverse('post:update', args=[str(self.slug)])
    
    def get_delete_url(self):
        return reverse('post:delete', args=[str(self.slug)])
    
    # bu fonksiyonda eşsiz slugları bulur
    def get_unique_slug(self):
        slug=slugify(self.title.replace('ı','i'))
        unique_slug=slug
        counter=1
        while Post.objects.filter(slug=unique_slug).exists():
            unique_slug='{}-{}'.format(slug,counter)
            counter+=1
        return unique_slug 


    
    def save(self,*args,**kwargs):
       
        self.slug = self.get_unique_slug()
        return super(Post,self).save(*args,**kwargs)
    

    class Meta:
        ordering=['-publishing_date']   

class Comment(models.Model):
    post=models.ForeignKey(Post,related_name='comments', on_delete=models.CASCADE)
    name=models.CharField(max_length=200,verbose_name="isim")
    content=models.TextField(verbose_name='yorum')
    created_date=models.DateTimeField(auto_now_add=True)
    

blog/post/forms.py
from django import forms
from .models import Post,Comment

class PostForm(forms.ModelForm):
    class Meta:
        model=Post
        fields=[
            'title',
            'content',
            'image',

        ]

class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields=[
            'name',
            'content',
           

        ]

blog/post/views.py
from django.shortcuts import render,HttpResponse, get_object_or_404,HttpResponseRedirect,redirect,Http404
from django.http import HttpResponseNotFound
from . models import Post
from .forms import PostForm,CommentForm
from django.contrib import messages
from django.utils.text import slugify
from django.db.models import Q

def post_index(request):
    post_list = Post.objects.all()
    query = request.GET.get('q')
    if query:
        post_list = post_list.filter(title__icontains=query)
    return render(request, 'post/index.html', {'postk': post_list})#en sağdaki posts veritabanımızdan gelenler tırnak içine yazılan posts templatede for  içinde kullanılacak




def post_detail(request, slug):
    post=get_object_or_404(Post, slug=slug)
    post.views_count += 1
    post.save()
    
    form=CommentForm(request.POST or None  )

    if form.is_valid():
        comment=form.save(commit=False)
        comment.post = post
        comment.save()
        return HttpResponseRedirect(post.get_absolute_url())
    context={
        'post':post,
        'form':form
    }
    return render(request,'post/detail.html',context)





def post_create(request):
    #form = PostForm()#form nesnesi urettim
    if not request.user.is_authenticated:  
        return HttpResponseNotFound

    form=PostForm(request.POST or None , request.FILES or None )

    if form.is_valid():
        post=form.save(commit=False)
        post.user = request.user
        post.save()
        messages.success(request,'başarılı bir şekilde oluşturuldu')
        return HttpResponseRedirect(post.get_absolute_url())

    context = {
        'form': form,
    }
    return render(request,'post/form.html',context)






def post_update(request,slug):
    if not request.user.is_authenticated: 
        return HttpResponseNotFound()
    
    post = get_object_or_404(Post, slug=slug)

    form=PostForm(request.POST or None, request.FILES or None , instance=post)
    if form.is_valid():
        form.save()
        messages.success(request, 'başarılı bir şekilde güncellendi')
        return HttpResponseRedirect(post.get_absolute_url())
    context = {
        'form': form,
    }

    return render(request,'post/form.html',context)







def post_delete(request,slug):
    if not request.user.is_authenticated:  #kullanici giriş yapmış ise
        return HttpResponseNotFound()
    post = get_object_or_404(Post, slug=slug)
    post.delete()
    return redirect('post:index')

blog/templates/post/comment.html
{% load crispy_forms_tags %}

<form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" class="btn btn-primary" value="gönder" />
</form>

blog/templates/post/detail.html
            

            {% extends 'base.html'%}
            

            {% block body%}
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 col-md-4">
                        <div class="thumbnail">
                                    {% if post.image %}
                                        <img src="{{ post.image.url }}" class="img-responsive">
                                    {% endif %}
                            <div class="caption">
                                <h3>{{ post.title }} <small>{{ post.publishing_date}}</small></h3>
                                {% if post.user %}
                                        {% if post.user.get_full_name %}
                                            <h4>yazar: {{ post.user.get_full_name }}</h4>
                                        {% else %}
                                            <h4>yazar: {{ post.user.username }}</h4>
                                        {% endif %}
                                    {% else %}
                                        <h4>yazar: Bilinmeyen yazar</h4>
                                    {% endif %}
                                <p>{{ post.content}}</p>
                                <p><a href="{% url 'post:detail' slug=post.slug %}" class="btn btn-primary" role="button">detay sayfasına git</a></p>
                                {% if request.user.is_authenticated %}
                                    <a href="{% url 'post:update' slug=post.slug %}" class="btn btn-primary" role="button">güncelle</a>
                                    <a href="{% url 'post:delete' slug=post.slug %}" class="btn btn-primary" role="button">sil</a>
                                {% endif %}
                            </div>
                        </div>
                        <br><br><br>
                      <h3>Buraya yorum ekleyebilirsiniz:</h3>  
                      {% include 'post/comment.html' %}
                      <hr>
                      {% for comment in post.comments.all %}

                      <h4>{{ comment.name }}| <small>{{ comment.created_date|timesince  }} önce</small></h4> 
                      <p>{{ comment.content|linebreaks}}</p>
                      <hr>

                      {% endfor %}
                    </div>
                </div>
            </div>

            {% endblock %}

blog/templates/post/form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}
   
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <h1> Yeni Post Oluştur</h1>
                    {{ form|crispy }}
                    <input class="btn btn-primary" type="submit" value="ekle">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/post/header.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        .navbar-nav li a {
            text-decoration: none;
        }
    </style>
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}">TREND POSTLAR</a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    {% if request.user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'post:create' %}">POST EKLE</a>
                        </li>
                    {% endif %}
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'post:index' %}">BLOGLAR</a>
                        </li>


                        <li class="nav-item ">
                            <a class="nav-link" href="{% url 'contact' %}">İLETİŞİM</a>
                        </li>
                    
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0"> <!-- İkinci ul bloğu burada başlıyor -->
                    {% if not request.user.is_authenticated %}
                        <li><a href="{% url 'accounts:register' %}">ÜYE OL</a></li>
                        <li><a href="{% url 'accounts:login' %}">GİRİŞ YAP</a></li>
                    {% else %}
                        <li><a href="{% url 'accounts:logout' %}">ÇIKIŞ YAP</a></li>
                    {% endif %}
                        </ul> <!-- İkinci ul bloğu burada bitiyor -->
                </ul>

                <form class="form-inline ml-auto" role="search" method="GET">
                    <div class="input-group">
                        <input class="form-control" type="text" name="q" placeholder="Postların içinde ara" value="{{ request.GET.q }}">
                        <span class="input-group-btn">
                            <input class="btn btn-default" type="submit" value="Ara">
                        </span>
                    </div>
                </form>

            </div>
        </div>
    </nav>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>

blog/templates/post/index.html
            {% extends 'base.html'%}
            

            {% block body%}
            

               

              <div class="container">
                {% for post in postk %}
                <div class="card" style="width: 50rem;">
                    {% if post.image %}
                        <img src="{{ post.image.url }}" class="img-responsive">
                    {% endif %}
                    <div class="card-body">
                      <h5 class="card-title">{{ post.title }}<small>{{ post.publishing_date|timesince}} önce</small></h5>
                      <p class="card-text"><h3>içerik</h3> <p>{{ post.content|linebreaks}}</p>
                      {% if post.user %}
                      {% if post.user.get_full_name %}
                          <h4>yazar: {{ post.user.get_full_name }}</h4>
                      {% else %}
                          <h4>yazar: {{ post.user.username }}</h4>
                      {% endif %}
                  {% else %}
                      <h4>yazar: Bilinmeyen yazar</h4>
                  {% endif %}
                  <h4>Görüntülenme Sayısı: {{ post.views_count }}</h4>
                     
                    </div>
                    
                    <div class="card-body">
                        <a href="{% url 'post:detail' slug=post.slug %}" class="btn btn-primary" role="button">oku</a>
                      
                            {% if request.user.is_authenticated %}
                                <a href="{% url 'post:update' slug=post.slug %}" class="btn btn-primary" role="button">güncelle</a>
                                <a href="{% url 'post:delete' slug=post.slug %}" class="btn btn-danger" role="button">sil</a>
                            {% endif %}
                   
                    </div>
                    
                </div>
                


                
                  

                    
                {% endfor %}
               
            {% endblock %}